# Generated by Django 5.1.3 on 2025-02-14 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swishcoin', '0002_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blockchain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField(unique=True)),
                ('timestamp', models.CharField(max_length=255)),
                ('transactions', models.TextField()),
                ('previous_hash', models.CharField(max_length=64)),
                ('nonce', models.IntegerField()),
                ('hash', models.CharField(max_length=64)),
            ],
        ),
    ]
