# Generated by Django 5.1.3 on 2025-02-14 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swishcoin', '0004_transaction_mined'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blockchain',
            name='index',
        ),
        migrations.RemoveField(
            model_name='blockchain',
            name='transactions',
        ),
        migrations.AlterField(
            model_name='blockchain',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
