# Generated by Django 5.1.3 on 2025-02-14 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swishcoin', '0005_remove_blockchain_index_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blockchain',
            new_name='Block',
        ),
    ]
